name:                advent21
version:             0.1.0.0
github:              "baffalop/advent21"
license:             BSD3
author:              "Nikita Gaidakov"
maintainer:          "nikita.gaidakov@gmail.com"
copyright:           "2021 Nikita Gaidakov"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Solutions to Advent of Code 2021 in Haskell

dependencies:
- base >= 4.7 && < 5
- extra
- optparse-applicative
  
library:
  source-dirs: src

executables:
  advent21-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - advent21

tests:
  advent21-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - advent21
